[env:esp32doit-devkit-v1]
platform = espressif32@3.3.0
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

[env:esp32-s3-devkitm-1]
platform = espressif32@3.3.0
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600